---
repos:
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.33.0 # or higher tag
      hooks:
          - id: yamllint
            args: [--format, parsable, -d, '{extends: relaxed, rules: {line-length: {max: 200}}}']
            exclude: scripts/esi.yml

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3 # or other specific tag
      hooks:
          - id: yamlfmt
            args: [--preserve-quotes]
            exclude: scripts/esi.yml

    - repo: https://github.com/compilerla/conventional-pre-commit
      rev: v3.0.0
      hooks:
          - id: conventional-pre-commit
            stages: [commit-msg]
