---
name: Release process

on:  # yamllint disable-line rule:truthy
    pull_request:
        branches: ['**']
        types: [closed]
    workflow_dispatch:  # Allow to be triggered manually for now.

permissions:
    contents: read  # to fetch code (actions/checkout)

jobs:
    # Create new releases of linuxcnc-ethercat using a version of the Semantic Release
    # method.  This draws release notes from properly-formatted commit messages.
    release:
        env:
            CHANGELOG_AUTHOR_NAME: "Scott Laird"
            CHANGELOG_AUTHOR_EMAIL: "scott@sigkill.org"
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.19

            - name: Release code
              uses: go-semantic-release/action@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

