---
name: Release process

on:  # yamllint disable-line rule:truthy
    pull_request:
        branches: ['**']
        types: [closed]
    workflow_dispatch:  # Allow to be triggered manually for now.

permissions:
    contents: read  # to fetch code (actions/checkout)

jobs:
    # Create new releases of linuxcnc-ethercat using a version of the Semantic Release
    # method.  This draws release notes from properly-formatted commit messages.
    release:
        env:
            CHANGELOG_AUTHOR_NAME: "Scott Laird"
            CHANGELOG_AUTHOR_EMAIL: "scott@sigkill.org"
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.19

            - name: Release code
              uses: go-semantic-release/action@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            # Stop here if no release is created.
            - name: Patch changelog (snapshot)
              #if: steps.release.outputs.changelog != ''
              id: bump_changelog
              env:
                  DEBEMAIL: ${{ env.CHANGELOG_AUTHOR_EMAIL }}
                  DEBFULLNAME: ${{ env.CHANGELOG_AUTHOR_NAME }}
              run: |
                  set -e
                  sudo apt install git-buildpackage
                  bgp dch -R -N ${{ steps.release.outputs.version }}

            - name: Determine current version
              run: |
                  sudo apt install -y dpkg-dev
                  echo "CURRENT_VERSION=$(dpkg-parsechangelog -Sversion)" >> $GITHUB_ENV

            - name: Submit the last change to Git
              run: |
                  # from https://gist.github.com/Broxzier/1ed980b8b3822d213e98042fc6a92040
                  git config --global user.email "scott+github-bot@sigkill.org"
                  git config --global user.name "LinucCNC-Ethercat git bot"
                  git add debian/changelog
                  git commit -m 'Automatically update debian/changelog for ${{ env.CURRENT_VERSION }}'
                  git push
                  echo "complete"
